name: api_collection
description: A side project, collecting and creating API wrapper from online APIs
version: 1.0.1

environment:
  sdk: ^3.0.6

dependencies:
  crypto: ^3.0.3
  dio: ^5.3.0
  jiffy: ^6.2.1

dev_dependencies:
  lint: ^2.1.2
